### ISSUE TITLE
avoid query to user when inst/doc occupied?

### ISSUE THREAD

**Issue by vjcitn** [r-lib/rcmdcheck#147] opened 2021-06-14 22:24 UTC
is it possible to avoid this situation?:
```
> rcmdcheck::rcmdcheck("parody")
── R CMD build ─────────────────────────────────────────────────────────────────
Building the package will delete...
  '/private/tmp/parody/inst/doc'
Are you sure?

1: Yes
2: No
```
I can't quite tell where this query is coming from -- but it doesn't happen for R CMD check.  I would
like to be able to set an option that allows deletion of the contents in inst/doc without approval.

**Comment by gaborcsardi** [comment] 2021-06-15 09:12
I think this is a duplicate of #130

**Closed by gaborcsardi** 2021-06-15 09:12 UTC
