### ISSUE TITLE
Fresh warning: Warning: Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release. A separate `actions/cache/restore` step should be used instead. See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.

### ISSUE THREAD

**Issue by zhuxr11** [r-lib/rcmdcheck#228] opened 2024-10-16 16:28 UTC
Fresh warning on github `R-CMD-CHECK.yaml`, seen just now (`usethis@2.2.3`):

Warning: Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release.
A separate `actions/cache/restore` step should be used instead.
See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.

**Comment by gaborcsardi** [comment] 2024-10-16 16:31
Duplicate of https://github.com/r-lib/actions/issues/928

**Closed as completed by gaborcsardi** 2024-10-16 16:31 UTC
