### ISSUE TITLE
Summary colours should match detail colours

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#66] opened 2018-05-01 14:24 UTC
For example I think NOTEs should be coloured orange, not red.

<img width="483" alt="screen shot 2018-05-01 at 7 23 34 am" src="https://user-images.githubusercontent.com/4196/39476376-9748efb6-4d10-11e8-8e8f-93d9a9545cd8.png">

**Comment by gaborcsardi** [comment] 2018-09-01 16:13
Duplicate of #54, fixed.

**Closed by gaborcsardi** 2018-09-01 16:13 UTC
