### ISSUE TITLE
check() and build() hang if DESCRIPTION file is malformed

### ISSUE THREAD

**Issue by ms609** [r-lib/rcmdcheck#90] opened 2018-11-02 11:44 UTC
I'm running devtools 2.0.1 on R3.5.1, Windows 10.

When I run `check()` or `build()`, R hangs at 
```
    v  checking for file 'C:\path\to\package/DESCRIPTION' ... 
```

The terminal looks "busy", but never progresses.  This occurs whether I run the function from the console, or from within RStudio.

When I run `R CMD check` in the Windows Command Prompt, I receive an error message and `CMD check` completes:

```
C:\Research\R>R CMD check Quartet
* using log directory 'C:/Research/R/Quartet.Rcheck'
* using R version 3.5.1 (2018-07-02)
* using platform: i386-w64-mingw32 (32-bit)
* using session charset: ISO8859-1
* checking for file 'Quartet/DESCRIPTION' ... ERROR
Required fields missing or empty:
  'Author' 'Maintainer'
* DONE

Status: 1 ERROR
```
The problem with the [description file](https://raw.githubusercontent.com/ms609/SlowQuartet/f75d0bf89359581b343f9a9e1868dc06dd8fc08f/DESCRIPTION) turns out to be that I'd `Suggests:`ed a package, rtqdist, that is not available on CRAN, without specifying a path to the package under the `Remotes:` field.  

I would expect devtools to report this as an error (as happened using `R CMD check` once I'd added a dummy `Author:` and `Maintainer:` field to the DESCRIPTION file, rather than hanging.

**Comment by gaborcsardi** [comment] 2018-11-05 16:20
I am pretty sure that this has nothing to do with the missing fields in `DESCRIPTION`, see my output below.

It seems that pkgbuild maybe copies the whole data-raw directory, even if it is in `.Rbuildignore.  Let me take a closer look.

```
❯ rcmdcheck("bad3")
── R CMD build ─────────────────────────────────────────────────────────────────
✔  checking for file ‘.../DESCRIPTION’ ...
─  preparing ‘badpackage’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘badpackage_1.0.0.tar.gz’

── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpXiV3Yg/file170bfb03ba5e/badpackage.Rcheck’
─  using R version 3.5.1 (2018-07-02)
─  using platform: x86_64-apple-darwin15.6.0 (64-bit)
─  using session charset: UTF-8
E  checking for file ‘badpackage/DESCRIPTION’
   Required fields missing or empty:
     ‘Author’ ‘Maintainer’

   See
     ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpXiV3Yg/file170bfb03ba5e/badpackage.Rcheck/00check.log’
   for details.

── R CMD check results ─────────────────────────────────── badpackage 1.0.0 ────
Duration: 412ms

❯ checking for file ‘badpackage/DESCRIPTION’ ... ERROR
  Required fields missing or empty:
    ‘Author’ ‘Maintainer’

1 error ✖ | 0 warnings ✔ | 0 notes ✔
```

**Comment by gaborcsardi** [comment] 2018-11-05 16:29
Oh, OK, good to know. :) So this is not a bug in pkgbuild of rcmdcheck then. 

I wonder if we can improve the current behavior, though. I guess the problem is that the extra files  and directories are sometimes used during `R CMD build`.

**Comment by gaborcsardi** [comment] 2018-11-05 17:46
I'll close this now and will open another issue for the possibly no-copy improvement in pkgbuild.

**Closed by gaborcsardi** 2018-11-05 17:46 UTC
